### ISSUE TITLE
Proveriti - nedostaje negacija?

### ISSUE THREAD

**Issue by VuceticBranislav** [NikolaVetnic/BRAINS2020_O#1]
https://github.com/NikolaVetnic/BRAINS2020_O/blob/31d526d42861b43e246efab72fe5c37e9ca62285/src/zadaci/s087/Motor.java#L37

Ovde ide negacija ako se nevaram:
`if (!radi())`

**Comment by NikolaVetnic** [comment]
Popravio i commitovao novo.
